from ui_icons import Icons
LOCALES = {
    "en": {
        "system_sync": f"{Icons.SYNC} CONNECTION",
        "synchro_subtitle": "Pick a channel and let's get the music started!",
        "standby_mode": f"{Icons.STANDBY} STANDBY",
        "standby_subtitle": "Pick a room where you want to listen to the radio.",
        "now_playing": "NOW PLAYING",
        "paused": "PAUSED",
        "idle": "IDLE",
        "stopped": "STOPPED",
        "presence_listening": "Listening to:",
        "presence_paused": "Paused",
        "artist": "Artist",
        "uploader": "Uploader",
        "title": "Title",
        "album": "Album",
        "genre": "Genre",
        "duration": "Length",
        "likes": "Likes",
        "dislikes": "Dislikes",
        "year": "Year",
        "label": "Label",
        "catnum": "#CAT",
        "source": "Source",
        "platform": "Platform",
        "play_count_label": "Plays",
        "last_played_label": "Last played",
        "details_label": "Info",
        "history_title": "What's played so far?",
        "history_label": "History",
        "stats_label": "Stats",
        "stats_title": f"{Icons.STATS} STATISTICS",
        "stats_weekly": "Weekly",
        "stats_monthly": "Monthly",
        "stats_all_time": "All Time",
        "top_artists": "Top 5 Artists",
        "top_songs": "Top 5 Songs",
        "top_listeners": "Top Listeners",
        "played_at": "Played at:",
        "date_format": "%Y-%m-%d %H:%M",
        "filter_label": "Filter",
        "filter_modal_title": "Filter by date",
        "filter_from_label": "From (YYYY.MM.DD)",
        "filter_to_label": "To (YYYY.MM.DD)",
        "date_invalid_error": "Date error! Use YYYY.MM.DD",
        "clear_filter_label": "Clear Filter",
        "delete_history_label": "Clear History",
        "delete_history_confirm": "Are you sure? You can't undo clearing the history!",
        "history_cleared": "History cleared.",
        "shuffle_label": "Shuffle",
        "edit_queue_label": "Edit Queue",
        "clear_queue_label": "Clear Queue",
        "clear_queue_confirm": "Are you sure you want to clear the whole queue?",
        "remove_song_label": "Delete",
        "shuffle_feedback": "Queue shuffled!",
        "up_next": "Up Next",
        "empty": "Empty",
        "tuned_by": "Requested by:",
        "location": "Channel:",
        "placeholder_freq": "Pick a channel",
        "placeholder_genre": "Pick a genre",
        "placeholder_lang": "Language",
        "placeholder_ui": "UI Style",
        "syncing": "Connecting...",
        "severing": "Disconnecting...",
        "switching_genre": "Switching to:",
        "resuming": "Resuming...",
        "cannot_pause_stopped": "You can't pause music while it's stopped.",
        "resuming_feedback": "Back to the music...",
        "pausing": "Pausing...",
        "stopping": "Stopping...",
        "forwarding": "Next track...",
        "randomizing": "Random song...",
        "nothing_playing": "Nothing's playing right now.",
        "cannot_seek_stopped": "You can't seek while the radio is stopped.",
        "back_error": "Nothing left in history to go back to!",
        "cooldown_error": "Hold on a sec, the system is resting...",
        "jump_modal_title": "Jump to time",
        "timestamp_input_label": "Where should we jump? (mm:ss)",
        "format_error": "Use the mm:ss format!",
        "no_current_track": "Nothing to jump to.",
        "too_long": "The track isn't that long.",
        "jumping": "Jumping to:",
        "vol_modal_title": "Volume (0-100%)",
        "vol_input_label": "Set percentage",
        "invalid_number": "That's not a number!",
        "vol_range_error": "Enter a number between 0 and 100.",
        "vol_set": "Volume set to:",
        "no_playing_error": "Nothing's playing.",
        "liked": "Liked:",
        "like_withdrawn": "Like removed:",
        "liked_replaced": "Liked (switched):",
        "disliked": "Disliked:",
        "dislike_withdrawn": "Dislike removed:",
        "disliked_replaced": "Disliked (switched):",
        "record_error": "Failed to save.",
        "play_label": "Play",
        "pause_label": "Pause",
        "stop_label": "Stop",
        "forward_label": "Next",
        "random_label": "Random",
        "seek_label": "Seek",
        "back_label": "Back",
        "vol_label": "Volume",
        "like_label": "Like",
        "dislike_label": "Not for me",
        "details_btn_label": "Info",
        "queue_label": "Queue",
        "sever_uplink": "Exit",
        "info_visibility": "Info Window",
        "queue_visibility": "Queue Window",
        "add_genre_label": "Add Genre",
        "add_genre_modal_title": "New Genre and Folders",
        "genre_name_label": "What should it be called?",
        "folder_paths_label": "Folder paths (comma separated)",
        "genre_added_success": "New genre (**{genre}**) added, scanning now!",
        "invalid_input": "Something went wrong with the input!",
        "admin_only": "You need to be an admin or system administrator for this.",
        "shown": "Shown",
        "hidden": "Hidden",
        "search_label": "Search",
        "library_label": "Library",
        "search_modal_title": "Search Library",
        "search_input_label": "Type something (artist, title, album...)",
        "search_no_results": "No results for:",
        "add_to_queue": "Added to queue:",
        "songs_tab": "Songs",
        "artists_tab": "Artists",
        "albums_tab": "Albums",
        "playlists_tab": "Lists",
        "page": "Page",
        "songs": "songs",
        "results": "results",
        "initiated_by": "Requested by:",
        "queue_all": "Queue all",
        "add_all": "Add all",
        "bulk_added_to_playlist": "Added {count} songs to the list.",
        "bulk_added_to_queue": "Added {count} songs to the queue.",
        "last_label": "Last",
        "reset_radio_label": "Reset Radio",
        "radio_reset_feedback": "Back to random mode.",
        "no_permission": "You don't have permission for this channel (or your role is too low).",
        "no_permission_general": "You don't have permission for this.",
        "playlist_studio_label": "List Studio",
        "playlist_studio_title": f"{Icons.STUDIO} LIST STUDIO",
        "playlist_studio_subtitle": "Manage and edit your playlists here.",
        "new_playlist_label": "New List",
        "delete_playlist_label": "Delete List",
        "select_playlist_placeholder": "Pick a list to edit",
        "playlist_editor_title": f"{Icons.PLAYLIST} EDITING LIST",
        "list_editor_title": f"{Icons.PLAYLIST} EDITING PLAYLIST",
        "save_exit_label": "Save & Exit",
        "create_playlist_modal_title": "Create New List",
        "playlist_name_label": "List name",
        "song_added_to_playlist": "Added to list:",
        "song_removed_from_playlist": "Removed from list:",
        "playlist_deleted": "Playlist deleted.",
        "rename_playlist_label": "Rename",
        "studio_locked_message": "The Studio is being used by {user}. Wait until they're done!",
        "ui_mode_label": "UI Style",
        "ui_mode_full": "Full (Icons + Labels)",
        "ui_mode_compact": "Compact (Icons only)",
        "rescan_label": "Update Library",
        "rescanning": "Checking things out... Please wait.",
        "rescan_complete": "Scan done! Found {inserted} new tracks, {skipped} unchanged.",
        "feedback_label": "Feedback",
        "feedback_modal_title": "Write to us!",
        "feedback_type_label": "What's it about?",
        "feedback_type_bug": "Report Bug",
        "feedback_type_feature": "Suggest Feature",
        "feedback_type_music": "Request Music",
        "feedback_content_label": "Details...",
        "feedback_music_content_label": "Artist - Title (and link if you have one)",
        "feedback_sent": "Got the feedback, thanks!",
        "added_to_favs": "Added to your favorites:",
        "removed_from_favs": "Removed from your favorites:",
        "fav_add_label": "Favorite",
        "fav_rem_label": "Not a favorite",
        "path_update_label": "Update Data",
        "path_update_modal_title": "Update tags from folder",
        "path_input_label": "Enter the exact folder path here",
        "updating_tags": "Updating data... Please wait.",
        "update_complete": "Update done! {inserted} tracks updated, {skipped} stayed the same.",
        "unauthorized_path": "This folder is not in the allowed locations. Access denied.",
        "weblink_label": "Web Link",
        "weblink_modal_title": "Request Web Link",
        "weblink_input_label": "YouTube / SoundCloud URL",
        "weblink_processing": "Processing link, please wait...",
        "weblink_error": "Invalid or unsupported link!",
        "weblink_added": "Link added to queue!",
        "online_mode_label": "Online Mode",
        "online_mode_on": "Online Mode: ON",
        "online_mode_off": "Online Mode: OFF",
        "online_mode_subtitle": "Listen exclusively to web links (YT/SC) with no local library.",
        "online_mode_title": f"{Icons.GLOBE} WEB-ONLY RADIO"
    },
    "hu": {
        "system_sync": f"{Icons.SYNC} CSATLAKOZÁS",
        "synchro_subtitle": "Válassz egy csatornát, és már indul is a zene!",
        "standby_mode": f"{Icons.STANDBY} KÉSZENLÉT",
        "standby_subtitle": "Válassz egy szobát, ahol hallgatni szeretnéd a rádiót.",
        "now_playing": "MOST SZÓL",
        "paused": "SZÜNETEL",
        "idle": "IDLE (ÜRESJÁRAT)",
        "stopped": "LEÁLLÍTVA",
        "presence_listening": "Hallgatja:",
        "presence_paused": "Megállítva",
        "artist": "Előadó",
        "uploader": "Feltöltő",
        "title": "Cím",
        "album": "Album",
        "genre": "Stílus",
        "duration": "Hossz",
        "likes": "Kedvelés",
        "dislikes": "Nem tetszik",
        "year": "Év",
        "label": "Kiadó",
        "catnum": "Katalógus #",
        "source": "Forrás",
        "platform": "Platform",
        "play_count_label": "Lejátszások",
        "last_played_label": "Utoljára szólt",
        "details_label": "Infó",
        "history_title": "Mik szóltak eddig?",
        "history_label": "Előzmények",
        "stats_label": "Statisztika",
        "stats_title": f"{Icons.STATS} STATISZTIKÁK",
        "stats_weekly": "Heti",
        "stats_monthly": "Havi",
        "stats_all_time": "Összesített",
        "top_artists": "Top 5 Előadó",
        "top_songs": "Top 5 Szám",
        "top_listeners": "Legnagyobb hallgatók",
        "played_at": "Ekkor szólt:",
        "date_format": "%Y.%m.%d %H:%M",
        "filter_label": "Szűrés",
        "filter_modal_title": "Szűrés dátumra",
        "filter_from_label": "Mikortól (ÉÉÉÉ.HH.NN)",
        "filter_to_label": "Meddig (ÉÉÉÉ.HH.NN)",
        "date_invalid_error": "Dátumhiba! Használd ezt: ÉÉÉÉ.HH.NN",
        "clear_filter_label": "Szűrő törlése",
        "delete_history_label": "Előzmények törlése",
        "delete_history_confirm": "Biztosan törölsz minden előzményt? Nem hozható vissza!",
        "history_cleared": "Előzmények törölve.",
        "shuffle_label": "Keverés",
        "edit_queue_label": "Lista szerkesztése",
        "clear_queue_label": "Lista ürítése",
        "clear_queue_confirm": "Biztosan törlöd a teljes várólistát?",
        "remove_song_label": "Törlés",
        "shuffle_feedback": "Lista megkeverve!",
        "up_next": "Következik",
        "empty": "Üres",
        "tuned_by": "Kérte:",
        "location": "Csatorna:",
        "placeholder_freq": "Válassz csatornát",
        "placeholder_genre": "Válassz stílust",
        "placeholder_lang": "Nyelvválasztás",
        "placeholder_ui": "Kezelőfelület",
        "syncing": "Csatlakozás...",
        "severing": "Lecsatlakozás...",
        "switching_genre": "Váltás:",
        "resuming": "Folytatás...",
        "cannot_pause_stopped": "Álló helyzetben nem tudod szüneteltetni.",
        "resuming_feedback": "Zene folytatása...",
        "pausing": "Szünet...",
        "stopping": "Leállítás...",
        "forwarding": "Következő szám...",
        "randomizing": "Véletlen zene...",
        "nothing_playing": "Most épp semmi nem szól.",
        "cannot_seek_stopped": "Álló helyzetben nem tudsz tekerni.",
        "back_error": "Nincs több előzmény, amin visszaléphetnél!",
        "cooldown_error": "Várj egy kicsit, pihen a rendszer...",
        "jump_modal_title": "Ugrás időpontra",
        "timestamp_input_label": "Melyik perchez ugorjunk? (pp:mp)",
        "format_error": "Használd a pp:mp formátumot!",
        "no_current_track": "Nincs mihez ugrani.",
        "too_long": "Ilyen hosszú nincs is ez a szám.",
        "jumping": "Ugrás ide:",
        "vol_modal_title": "Hangerő (0-100%)",
        "vol_input_label": "Hány százalék legyen?",
        "invalid_number": "Ez nem egy szám!",
        "vol_range_error": "0 és 100 között adj meg valamit.",
        "vol_set": "Hangerő beállítva:",
        "no_playing_error": "Nem szól semmi.",
        "liked": "Tetszik:",
        "like_withdrawn": "Mégsem tetszik:",
        "liked_replaced": "Inkább tetszik:",
        "disliked": "Nem tetszik:",
        "dislike_withdrawn": "Mégis tetszik:",
        "disliked_replaced": "Inkább nem tetszik:",
        "record_error": "Nem sikerült menteni.",
        "play_label": "Lejátszás",
        "pause_label": "Szünet",
        "stop_label": "Stop",
        "forward_label": "Következő",
        "random_label": "Véletlen",
        "seek_label": "Tekerés",
        "back_label": "Vissza",
        "vol_label": "Hangerő",
        "like_label": "Tetszik",
        "dislike_label": "Nem jön be",
        "details_btn_label": "Infó",
        "queue_label": "Lista",
        "sever_uplink": "Kilépés",
        "info_visibility": "Infó ablak",
        "queue_visibility": "Várólista ablak",
        "add_genre_label": "Stílus hozzáadása",
        "add_genre_modal_title": "Új stílus és mappák",
        "genre_name_label": "Mi legyen a neve?",
        "folder_paths_label": "Mappák útvonala (vesszővel elválasztva)",
        "genre_added_success": "Új stílus (**{genre}**) hozzáadva, már szkenneljük is!",
        "invalid_input": "Valamit rosszul írtál be!",
        "admin_only": "Ehhez adminnak vagy rendszergazdának kell lenned.",
        "shown": "Látszik",
        "hidden": "Rejtve",
        "search_label": "Keresés",
        "library_label": "Zenetár",
        "search_modal_title": "Keresés a zenék között",
        "search_input_label": "Írj be valamit (előadó, cím, album...)",
        "search_no_results": "Nincs találat erre:",
        "add_to_queue": "Hozzáadtuk a listához:",
        "songs_tab": "Dalok",
        "artists_tab": "Előadók",
        "albums_tab": "Albumok",
        "playlists_tab": "Listák",
        "page": "Oldal",
        "songs": "dal",
        "results": "találat",
        "initiated_by": "Kérte:",
        "queue_all": "Összeset a listához",
        "add_all": "Összes hozzáadása",
        "bulk_added_to_playlist": "{count} dal került a lejátszási listába.",
        "bulk_added_to_queue": "{count} dalt raktunk a várólistába.",
        "last_label": "Utolsó",
        "reset_radio_label": "Rádió alaphelyzet",
        "radio_reset_feedback": "Visszaálltunk véletlenszerű módra.",
        "no_permission": "Nincs jogod ehhez a csatornához (vagy a rangod kevés).",
        "no_permission_general": "Ehhez nincs jogosultságod.",
        "playlist_studio_label": "Lista Stúdió",
        "playlist_studio_title": f"{Icons.STUDIO} LISTA STÚDIÓ",
        "playlist_studio_subtitle": "Itt kezelheted és szerkesztheted a listáidat.",
        "new_playlist_label": "Új lista",
        "delete_playlist_label": "Lista törlése",
        "select_playlist_placeholder": "Válassz egy listát a szerkesztéshez",
        "playlist_editor_title": f"{Icons.PLAYLIST} LISTA SZERKESZTÉSE",
        "list_editor_title": f"{Icons.PLAYLIST} LISTA SZERKESZTÉSE",
        "save_exit_label": "Mentés és kilépés",
        "create_playlist_modal_title": "Új lista létrehozása",
        "playlist_name_label": "Lista neve",
        "song_added_to_playlist": "Hozzáadva a listához:",
        "song_removed_from_playlist": "Törölve a listáról:",
        "playlist_deleted": "Lejátszási lista törölve.",
        "rename_playlist_label": "Átnevezés",
        "studio_locked_message": "A Stúdiót épp {user} használja. Várd meg, amíg végez!",
        "ui_mode_label": "Kezelőfelület stílusa",
        "ui_mode_full": "Teljes (Ikonok + Feliratok)",
        "ui_mode_compact": "Kompakt (Csak ikonok)",
        "rescan_label": "Zenetár frissítése",
        "rescanning": "Dolgok átnézése... Várj egy kicsit.",
        "rescan_complete": "Kész a szken! {inserted} új dal, {skipped} változatlan.",
        "feedback_label": "Visszajelzés",
        "feedback_modal_title": "Írj nekünk!",
        "feedback_type_label": "Milyen témában?",
        "feedback_type_bug": "Hiba jelentése",
        "feedback_type_feature": "Ötlet beküldése",
        "feedback_type_music": "Zene kérése",
        "feedback_content_label": "Részletek...",
        "feedback_music_content_label": "Előadó - Cím (ha tudod, linket is dobhatsz)",
        "feedback_sent": "Megkaptuk a visszajelzést, köszi!",
        "added_to_favs": "Hozzáadva a kedvenceidhez:",
        "removed_from_favs": "Kiszedve a kedvenceid közül:",
        "fav_add_label": "Kedvenc",
        "fav_rem_label": "Már nem kedvenc",
        "path_update_label": "Adatok frissítése",
        "path_update_modal_title": "Tagek frissítése mappából",
        "path_input_label": "Itt add meg a mappa pontos helyét",
        "updating_tags": "Adatok frissítése... Kérlek várj.",
        "update_complete": "Frissítés kész! {inserted} dal frissítve, {skipped} maradt a régi.",
        "unauthorized_path": "Ez a mappa nincs benne a megengedett helyekben. Hozzáférés megtagadva.",
        "weblink_label": "Web Link",
        "weblink_modal_title": "Külső Link Hozzáadása",
        "weblink_input_label": "YouTube / SoundCloud URL",
        "weblink_processing": "Link feldolgozása, kis türelmet...",
        "weblink_error": "Érvénytelen vagy nem támogatott link!",
        "weblink_added": "Link hozzáadva a várólistához!",
        "online_mode_label": "Online Mód",
        "online_mode_on": "Online Mód: BE",
        "online_mode_off": "Online Mód: KI",
        "online_mode_subtitle": "Hallgass kizárólag webes linkeket (YT/SC) adatbázis nélkül.",
        "online_mode_title": f"{Icons.GLOBE} WEB-RÁDIÓ ÜZEMMÓD"
    }
}
_radio_ref = None

def init_translate(radio_instance):
    global _radio_ref
    _radio_ref = radio_instance

def t(key):
    lang = "en"
    if _radio_ref:
        lang = getattr(_radio_ref, "language", "en")
    current_locales = LOCALES.get(lang, LOCALES["en"])
    result = current_locales.get(key)
    if result is None:
        result = LOCALES["en"].get(key, key)
    return result
