name = "666radiobotai"
main = "Arbeiter/src/index.js"
compatibility_date = "2026-06-09"
workers_dev = true

[observability]
enabled = true

[vars]
PUBLIC_PROJECT_NAME = "666SOUNDsDESIGn WebRadio"
PUBLIC_BOT_NAME = "666 RadioBotAI"
PUBLIC_VERSION = "v1.1.0"
PUBLIC_WORKER_ROLE = "RadioBotAI API / Vocard Dashboard Bridge / Discord Shooter Control"
PUBLIC_WEBRADIO_BASE_URL = "https://webradio.666soundsdesign-broadcaster.com"
PUBLIC_MAIN_STREAM_URL = "https://webradio.666soundsdesign-broadcaster.com/stream"
PUBLIC_FALLBACK_STREAM_URL = "https://webradio.666soundsdesign-broadcaster.com/fallback-stream"
PUBLIC_NOWPLAYING_URL = "https://webradio.666soundsdesign-broadcaster.com/api/nowplaying"
PUBLIC_HEALTH_URL = "https://webradio.666soundsdesign-broadcaster.com/health"
PUBLIC_TUNEIN_URL = "https://tunein.com/radio/s357001"
